name: Bow Framework CI

on: [ push, pull_request ]

env:
  FTP_HOST: localhost
  FTP_USER: bob
  FTP_PASSWORD: 12345
  FTP_PORT: 21

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php: [8.1, 8.2]
        os: [ubuntu-latest]

    name: PHP-${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8mb4'
          collation server: 'utf8mb4_general_ci'
          mysql version: '5.7'
          mysql database: 'test_db'
          mysql root password: 'secret'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, mysql, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - run: docker run --net=host -p 21:21 -e USER=$FTP_USER -e PASS=$FTP_PASSWORD -d --name ftp -v $(pwd)/:/ftp/$FTP_USER emilybache/vsftpd-server
      - run: docker run -p 1080:1080 -p 1025:1025 -d --name maildev soulteary/maildev
      - run: docker run -d -p 11301:11300 schickling/beanstalkd

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}

      - name: Copy the php ini config
        run: cp php.dist.ini php.ini

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Create test cache directory
        run: if [ ! -d /tmp/bowphp_testing ]; then mkdir -p /tmp/bowphp_testing; fi;

      - name: Check code standard
        run: ./vendor/bin/phpcs --standard=psr12 --severity=4 --tab-width=4 src --ignore="tests"

      - name: Run test suite
        run: composer run-script test
